version: '3.7'

services:
  database:
    image: postgres
    container_name: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=facebook
    volumes:
      - pgdata:/data/postgres
    network_mode: host
  facebook:
    container_name: facebook-api
    build: .
    ports:
      - 3333:3333
    volumes:
      - .:/usr/facebook
    network_mode: host

volumes:
  pgdata:
    driver: local
