export { default as ProfileController } from './ProfileController'
export { default as AuthController } from './AuthController'
export { default as AvatarController } from './AvatarController'
export { default as PublicationController } from './PublicationController'
export { default as SearchController } from './SearchController'
export { default as CommentController } from './CommentController'
export { default as LikeController } from './LikeController'
